server:
    port: 8081
    error:
        include-message: always
        include-binding-errors: always
RedNet:
    app:
        accessTokenCookieName: rednet-jwt-access
        jwt:
            allowedClockSkewSeconds: 15
            secretKey: ${AUTH_JWT_SECRET_KEY}
